name: Build, Deploy, and Publish Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne (minuit)
  push:
    branches:
      - main  # Déclenche le workflow sur un push à la branche main
  workflow_dispatch:
    inputs:
      version:
        description: "Version de l'image Docker"
        required: true
        default: "latest"
  #------------------JOBS
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Go 1.23
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      #  Installer les dépendances
      - name: Install dependencies
        run: go mod tidy

      #  Compiler le code Go
      - name: Build Go program
        run: go build -o cowsay .

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use  # Créer et activer un builder multi-plateforme

   
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: battaba/cowsay-go:${{ github.event.inputs.version || 'latest' }} 

    
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cowsay-binary
          path: ./cowsay

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: cowsay-binary
          path: ./bin

      # Étape 2 : Déployer l'application (ajuster selon tes besoins)
      - name: Deploy application
        run: |
          chmod +x ./bin/cowsay
          nohup ./bin/cowsay "Hello from GitHub Actions!" &
          
  
      - name: Push to DockerHub
        run: |
          docker push battaba/cowsay-go:${{ github.event.inputs.version || 'latest' }}
