name: Build, Deploy, and Publish Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne (minuit)
  push:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      version:
        description: "Version de l'image Docker"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      
      - name: Install dependencies
        run: go mod tidy

      
      - name: Build Go program
        run: go build -o cowsay .


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    
      - name: Set up Docker Buildx
        run: |
          docker buildx create --use  # Créer et activer un builder multi-plateforme

    
      - name: Build Docker image
        run: |
          docker build -t battaba/cowsay-go:${{ github.event.inputs.version || 'latest' }} .

    
      - name: Push Docker image to Docker Hub
        run: |
          docker push battaba/cowsay-go:${{ github.event.inputs.version || 'latest' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
     
      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: cowsay-binary
          path: ./bin

    
      - name: Deploy application
        run: |
          chmod +x ./bin/cowsay
          nohup ./bin/cowsay "Hello from GitHub Actions!" &
