name: Deploy Go Application

on:
  push:
    branches:
      - main  # Déclenche le workflow sur un push à la branche main

jobs:
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: cowsay-binary
          path: ./bin      

      - name: Deploy application on server
        run: |
          # Si nécessaire, arrêter et supprimer les conteneurs Docker existants
          docker stop cowsay || true
          docker rm cowsay || true
          
          # Ajouter les permissions d'exécution au binaire téléchargé
          chmod +x ./bin/cowsay

          # Exécuter le binaire en arrière-plan (comme démon)
          nohup ./bin/cowsay "Hello from GitHub Actions!" &
